# Default values for kargo-boilerplate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project:
  create: true
projectConfig:
  create: true
  promotionPolicies: []
warehouse:
  create: true
  subscriptions: []
stages: []
analysisTemplates: []